# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    use_key_in_widget_constructors: true
    prefer_relative_imports: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "ios/**"
    - "android/**"
    - "web/**"
  errors:
    missing_required_param: error
    missing_return: error
    deprecated_member_use: ignore
  language:
    strict-casts: true
