buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.14'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')

    plugins.withId("com.android.library") {
        android {
            if (namespace == null) {
                namespace = "com.plugin.${project.name.replaceAll('-', '_')}"
            }
        }
    }
    plugins.withId("com.android.application") {
        android {
            if (namespace == null) {
                namespace = "com.plugin.${project.name.replaceAll('-', '_')}"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
